---
resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:((git-repo)).git
    private_key: ((github-private-key))
    branch: ((git-branch))

jobs:
- name: build
  serial: true
  plan:
  - get: source-code
    trigger: true
  - task: compile
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: maven
          tag: '3.5.3-jdk-8-alpine'
      inputs:
      - name: source-code
      run:
        path: mvn
        args: [ "-f", "source-code/pom.xml", "compile" ]
- name: test
  plan:
  - get: source-code
    passed: [build]
    trigger: true
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: maven
          tag: '3.5.3-jdk-8-alpine'
      inputs:
      - name: source-code
      run:
        path: mvn
        args: [ "-f", "source-code/pom.xml", "verify" ]
