resources:
  - name: source-code
    type: git
    source:
      uri: git@github.com:((git-repo)).git
      private_key: ((github-private-key))
      branch: ((git-branch))
  - name: tasks-source
    type: git
    source:
      uri: git@github.com:blockmar/concourse-maven.git
      private_key: ((github-private-key))
      branch: master

jobs:
  - name: build
    plan:
    - get: source-code
      trigger: true
    - get: tasks-source
      trigger: false
    - task: compile
      file: tasks-source/tasks/maven-compile.yml
  - name: test
    plan:
    - get: tasks-source      
    - get: source-code
      passed: [build]
      trigger: true
    - task: test
      file: tasks-source/tasks/maven-test.yml
